# -*- mode: python ; coding: utf-8 -*-
"""
KivyMD Chat UI PyInstaller Specification
Auto-generated by create_pyinstaller_spec.py
"""

import os
import sys
from pathlib import Path
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

# Get project root (absolute path since __file__ not available in spec context)
project_root = Path(r"/home/human/AAREPOS/KIVY_UI")

# Application metadata
app_name = "KivyChatUI"
app_version = "0.1.0"
app_description = "Modern KivyMD Chat UI Frontend"

# Main script
main_script = str(project_root / "main.py")

# Data files to include
kivymd_data = collect_data_files("kivymd")
kivy_data = collect_data_files("kivy")

# Include chat_ui package data
chat_ui_data = []
chat_ui_path = project_root / "chat_ui"
if chat_ui_path.exists():
    for file_path in chat_ui_path.rglob("*"):
        if file_path.is_file() and not file_path.name.startswith('.'):
            rel_path = file_path.relative_to(project_root)
            chat_ui_data.append((str(file_path), str(rel_path.parent)))

# Include platform_utils
platform_utils_data = []
platform_utils_path = project_root / "platform_utils"
if platform_utils_path.exists():
    for file_path in platform_utils_path.rglob("*.py"):
        if file_path.is_file():
            rel_path = file_path.relative_to(project_root)
            platform_utils_data.append((str(file_path), str(rel_path.parent)))

# Java files (for reference, not included in Linux build)
java_data = []
java_path = project_root / "java"
if java_path.exists():
    for file_path in java_path.rglob("*.java"):
        if file_path.is_file():
            rel_path = file_path.relative_to(project_root)
            java_data.append((str(file_path), str(rel_path.parent)))

# Combine all data files
datas = kivymd_data + kivy_data + chat_ui_data + platform_utils_data + java_data

# Hidden imports for KivyMD and dependencies
hiddenimports = [
    # Core Kivy modules
    'kivy.core.window',
    'kivy.core.image',
    'kivy.core.clipboard',
    'kivy.core.text',
    'kivy.core.audio',
    'kivy.graphics',
    'kivy.graphics.texture',
    'kivy.graphics.svg',
    'kivy.metrics',
    'kivy.utils',
    'kivy.clock',
    'kivy.lang',
    'kivy.factory',
    'kivy.properties',
    'kivy.event',
    'kivy.logger',
    'kivy.config',
    
    # KivyMD modules
    'kivymd',
    'kivymd.app',
    'kivymd.uix',
    'kivymd.uix.screen',
    'kivymd.uix.boxlayout',
    'kivymd.uix.card',
    'kivymd.uix.label',
    'kivymd.uix.textfield',
    'kivymd.uix.button',
    'kivymd.uix.scrollview',
    'kivymd.theming',
    'kivymd.color_definitions',
    'kivymd.font_definitions',
    'kivymd.icon_definitions',
    'kivymd.material_resources',
    
    # Application modules
    'chat_ui',
    'chat_ui.config',
    'chat_ui.modern_chat',
    'chat_ui.theme',
    'chat_ui.websocket_client',
    'chat_ui.android_stt',
    'chat_ui.permissions',
    'platform_utils',
    'platform_utils.desktop',
    'platform_utils.android',
    
    # Dependencies
    'websockets',
    'asyncio',
    'concurrent.futures',
    'threading',
    'queue',
    'json',
    'logging',
    'pathlib',
    'plyer',
    'plyer.platforms.linux',
]

# PyInstaller Analysis
a = Analysis(
    [main_script],
    pathex=[str(project_root)],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Exclude unnecessary modules to reduce size
        'tkinter',
        'matplotlib',
        'numpy',
        'scipy',
        'PIL',
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
        'wx',
        'django',
        'flask',
        'tornado',
        'selenium',
        'requests',
        'urllib3',
        'certifi',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

# Remove duplicate data files
pyz = PYZ(a.pure, a.zipped_data, cipher=None)

# Create executable
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name=app_name,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # GUI application
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,  # Add icon path here if you have one
)

# Note: COLLECT section not needed for onefile builds
# The EXE section above creates a single executable file
